/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * API version: 0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
	"fmt"
)

// V0037Signal POSIX signal name
type V0037Signal string

// List of v0.0.37_signal
const (
	HUP V0037Signal = "HUP"
	INT V0037Signal = "INT"
	QUIT V0037Signal = "QUIT"
	ABRT V0037Signal = "ABRT"
	KILL V0037Signal = "KILL"
	ALRM V0037Signal = "ALRM"
	TERM V0037Signal = "TERM"
	USR1 V0037Signal = "USR1"
	USR2 V0037Signal = "USR2"
	URG V0037Signal = "URG"
	CONT V0037Signal = "CONT"
	STOP V0037Signal = "STOP"
	TSTP V0037Signal = "TSTP"
	TTIN V0037Signal = "TTIN"
	TTOU V0037Signal = "TTOU"
)

func (v *V0037Signal) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V0037Signal(value)
	for _, existing := range []V0037Signal{ "HUP", "INT", "QUIT", "ABRT", "KILL", "ALRM", "TERM", "USR1", "USR2", "URG", "CONT", "STOP", "TSTP", "TTIN", "TTOU",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V0037Signal", value)
}

// Ptr returns reference to v0.0.37_signal value
func (v V0037Signal) Ptr() *V0037Signal {
	return &v
}

type NullableV0037Signal struct {
	value *V0037Signal
	isSet bool
}

func (v NullableV0037Signal) Get() *V0037Signal {
	return v.value
}

func (v *NullableV0037Signal) Set(val *V0037Signal) {
	v.value = val
	v.isSet = true
}

func (v NullableV0037Signal) IsSet() bool {
	return v.isSet
}

func (v *NullableV0037Signal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0037Signal(val *V0037Signal) *NullableV0037Signal {
	return &NullableV0037Signal{value: val, isSet: true}
}

func (v NullableV0037Signal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0037Signal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

