/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044JobArrayLimitsMaxRunning type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044JobArrayLimitsMaxRunning{}

// V0044JobArrayLimitsMaxRunning struct for V0044JobArrayLimitsMaxRunning
type V0044JobArrayLimitsMaxRunning struct {
	// Maximum number of simultaneously running tasks, 0 if no limit
	Tasks *int32 `json:"tasks,omitempty"`
}

// NewV0044JobArrayLimitsMaxRunning instantiates a new V0044JobArrayLimitsMaxRunning object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044JobArrayLimitsMaxRunning() *V0044JobArrayLimitsMaxRunning {
	this := V0044JobArrayLimitsMaxRunning{}
	return &this
}

// NewV0044JobArrayLimitsMaxRunningWithDefaults instantiates a new V0044JobArrayLimitsMaxRunning object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044JobArrayLimitsMaxRunningWithDefaults() *V0044JobArrayLimitsMaxRunning {
	this := V0044JobArrayLimitsMaxRunning{}
	return &this
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *V0044JobArrayLimitsMaxRunning) GetTasks() int32 {
	if o == nil || IsNil(o.Tasks) {
		var ret int32
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobArrayLimitsMaxRunning) GetTasksOk() (*int32, bool) {
	if o == nil || IsNil(o.Tasks) {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *V0044JobArrayLimitsMaxRunning) HasTasks() bool {
	if o != nil && !IsNil(o.Tasks) {
		return true
	}

	return false
}

// SetTasks gets a reference to the given int32 and assigns it to the Tasks field.
func (o *V0044JobArrayLimitsMaxRunning) SetTasks(v int32) {
	o.Tasks = &v
}

func (o V0044JobArrayLimitsMaxRunning) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044JobArrayLimitsMaxRunning) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tasks) {
		toSerialize["tasks"] = o.Tasks
	}
	return toSerialize, nil
}

type NullableV0044JobArrayLimitsMaxRunning struct {
	value *V0044JobArrayLimitsMaxRunning
	isSet bool
}

func (v NullableV0044JobArrayLimitsMaxRunning) Get() *V0044JobArrayLimitsMaxRunning {
	return v.value
}

func (v *NullableV0044JobArrayLimitsMaxRunning) Set(val *V0044JobArrayLimitsMaxRunning) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044JobArrayLimitsMaxRunning) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044JobArrayLimitsMaxRunning) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044JobArrayLimitsMaxRunning(val *V0044JobArrayLimitsMaxRunning) *NullableV0044JobArrayLimitsMaxRunning {
	return &NullableV0044JobArrayLimitsMaxRunning{value: val, isSet: true}
}

func (v NullableV0044JobArrayLimitsMaxRunning) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044JobArrayLimitsMaxRunning) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


