/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044JobMcs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044JobMcs{}

// V0044JobMcs struct for V0044JobMcs
type V0044JobMcs struct {
	// Multi-Category Security label on the job
	Label *string `json:"label,omitempty"`
}

// NewV0044JobMcs instantiates a new V0044JobMcs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044JobMcs() *V0044JobMcs {
	this := V0044JobMcs{}
	return &this
}

// NewV0044JobMcsWithDefaults instantiates a new V0044JobMcs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044JobMcsWithDefaults() *V0044JobMcs {
	this := V0044JobMcs{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *V0044JobMcs) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobMcs) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *V0044JobMcs) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *V0044JobMcs) SetLabel(v string) {
	o.Label = &v
}

func (o V0044JobMcs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044JobMcs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableV0044JobMcs struct {
	value *V0044JobMcs
	isSet bool
}

func (v NullableV0044JobMcs) Get() *V0044JobMcs {
	return v.value
}

func (v *NullableV0044JobMcs) Set(val *V0044JobMcs) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044JobMcs) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044JobMcs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044JobMcs(val *V0044JobMcs) *NullableV0044JobMcs {
	return &NullableV0044JobMcs{value: val, isSet: true}
}

func (v NullableV0044JobMcs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044JobMcs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


