/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044StepTimeUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044StepTimeUser{}

// V0044StepTimeUser struct for V0044StepTimeUser
type V0044StepTimeUser struct {
	// User CPU time used by the step in seconds
	Seconds *int64 `json:"seconds,omitempty"`
	// User CPU time used by the step in microseconds
	Microseconds *int32 `json:"microseconds,omitempty"`
}

// NewV0044StepTimeUser instantiates a new V0044StepTimeUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044StepTimeUser() *V0044StepTimeUser {
	this := V0044StepTimeUser{}
	return &this
}

// NewV0044StepTimeUserWithDefaults instantiates a new V0044StepTimeUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044StepTimeUserWithDefaults() *V0044StepTimeUser {
	this := V0044StepTimeUser{}
	return &this
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *V0044StepTimeUser) GetSeconds() int64 {
	if o == nil || IsNil(o.Seconds) {
		var ret int64
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTimeUser) GetSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.Seconds) {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *V0044StepTimeUser) HasSeconds() bool {
	if o != nil && !IsNil(o.Seconds) {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int64 and assigns it to the Seconds field.
func (o *V0044StepTimeUser) SetSeconds(v int64) {
	o.Seconds = &v
}

// GetMicroseconds returns the Microseconds field value if set, zero value otherwise.
func (o *V0044StepTimeUser) GetMicroseconds() int32 {
	if o == nil || IsNil(o.Microseconds) {
		var ret int32
		return ret
	}
	return *o.Microseconds
}

// GetMicrosecondsOk returns a tuple with the Microseconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTimeUser) GetMicrosecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.Microseconds) {
		return nil, false
	}
	return o.Microseconds, true
}

// HasMicroseconds returns a boolean if a field has been set.
func (o *V0044StepTimeUser) HasMicroseconds() bool {
	if o != nil && !IsNil(o.Microseconds) {
		return true
	}

	return false
}

// SetMicroseconds gets a reference to the given int32 and assigns it to the Microseconds field.
func (o *V0044StepTimeUser) SetMicroseconds(v int32) {
	o.Microseconds = &v
}

func (o V0044StepTimeUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044StepTimeUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Seconds) {
		toSerialize["seconds"] = o.Seconds
	}
	if !IsNil(o.Microseconds) {
		toSerialize["microseconds"] = o.Microseconds
	}
	return toSerialize, nil
}

type NullableV0044StepTimeUser struct {
	value *V0044StepTimeUser
	isSet bool
}

func (v NullableV0044StepTimeUser) Get() *V0044StepTimeUser {
	return v.value
}

func (v *NullableV0044StepTimeUser) Set(val *V0044StepTimeUser) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044StepTimeUser) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044StepTimeUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044StepTimeUser(val *V0044StepTimeUser) *NullableV0044StepTimeUser {
	return &NullableV0044StepTimeUser{value: val, isSet: true}
}

func (v NullableV0044StepTimeUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044StepTimeUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


