/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * API version: 0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// V0037License struct for V0037License
type V0037License struct {
	// name of license
	Name *string `json:"name,omitempty"`
}

// NewV0037License instantiates a new V0037License object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0037License() *V0037License {
	this := V0037License{}
	return &this
}

// NewV0037LicenseWithDefaults instantiates a new V0037License object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0037LicenseWithDefaults() *V0037License {
	this := V0037License{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V0037License) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037License) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V0037License) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V0037License) SetName(v string) {
	o.Name = &v
}

func (o V0037License) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableV0037License struct {
	value *V0037License
	isSet bool
}

func (v NullableV0037License) Get() *V0037License {
	return v.value
}

func (v *NullableV0037License) Set(val *V0037License) {
	v.value = val
	v.isSet = true
}

func (v NullableV0037License) IsSet() bool {
	return v.isSet
}

func (v *NullableV0037License) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0037License(val *V0037License) *NullableV0037License {
	return &NullableV0037License{value: val, isSet: true}
}

func (v NullableV0037License) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0037License) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


