/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.2&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion{}

// V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion struct for V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion
type V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion struct {
	// Slurm release major version
	Major *string `json:"major,omitempty"`
	// Slurm release micro version
	Micro *string `json:"micro,omitempty"`
	// Slurm release minor version
	Minor *string `json:"minor,omitempty"`
}

// NewV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion instantiates a new V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion() *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion {
	this := V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion{}
	return &this
}

// NewV0041OpenapiSlurmdbdJobsRespMetaSlurmVersionWithDefaults instantiates a new V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdJobsRespMetaSlurmVersionWithDefaults() *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion {
	this := V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion{}
	return &this
}

// GetMajor returns the Major field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) GetMajor() string {
	if o == nil || IsNil(o.Major) {
		var ret string
		return ret
	}
	return *o.Major
}

// GetMajorOk returns a tuple with the Major field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) GetMajorOk() (*string, bool) {
	if o == nil || IsNil(o.Major) {
		return nil, false
	}
	return o.Major, true
}

// HasMajor returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) HasMajor() bool {
	if o != nil && !IsNil(o.Major) {
		return true
	}

	return false
}

// SetMajor gets a reference to the given string and assigns it to the Major field.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) SetMajor(v string) {
	o.Major = &v
}

// GetMicro returns the Micro field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) GetMicro() string {
	if o == nil || IsNil(o.Micro) {
		var ret string
		return ret
	}
	return *o.Micro
}

// GetMicroOk returns a tuple with the Micro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) GetMicroOk() (*string, bool) {
	if o == nil || IsNil(o.Micro) {
		return nil, false
	}
	return o.Micro, true
}

// HasMicro returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) HasMicro() bool {
	if o != nil && !IsNil(o.Micro) {
		return true
	}

	return false
}

// SetMicro gets a reference to the given string and assigns it to the Micro field.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) SetMicro(v string) {
	o.Micro = &v
}

// GetMinor returns the Minor field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) GetMinor() string {
	if o == nil || IsNil(o.Minor) {
		var ret string
		return ret
	}
	return *o.Minor
}

// GetMinorOk returns a tuple with the Minor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) GetMinorOk() (*string, bool) {
	if o == nil || IsNil(o.Minor) {
		return nil, false
	}
	return o.Minor, true
}

// HasMinor returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) HasMinor() bool {
	if o != nil && !IsNil(o.Minor) {
		return true
	}

	return false
}

// SetMinor gets a reference to the given string and assigns it to the Minor field.
func (o *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) SetMinor(v string) {
	o.Minor = &v
}

func (o V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Major) {
		toSerialize["major"] = o.Major
	}
	if !IsNil(o.Micro) {
		toSerialize["micro"] = o.Micro
	}
	if !IsNil(o.Minor) {
		toSerialize["minor"] = o.Minor
	}
	return toSerialize, nil
}

type NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion struct {
	value *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) Get() *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) Set(val *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion(val *V0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) *NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion {
	return &NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespMetaSlurmVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


