/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044JobTimeTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044JobTimeTotal{}

// V0044JobTimeTotal struct for V0044JobTimeTotal
type V0044JobTimeTotal struct {
	// Sum of System and User CPU time used by the job in seconds
	Seconds *int64 `json:"seconds,omitempty"`
	// Sum of System and User CPU time used by the job in microseconds
	Microseconds *int64 `json:"microseconds,omitempty"`
}

// NewV0044JobTimeTotal instantiates a new V0044JobTimeTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044JobTimeTotal() *V0044JobTimeTotal {
	this := V0044JobTimeTotal{}
	return &this
}

// NewV0044JobTimeTotalWithDefaults instantiates a new V0044JobTimeTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044JobTimeTotalWithDefaults() *V0044JobTimeTotal {
	this := V0044JobTimeTotal{}
	return &this
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *V0044JobTimeTotal) GetSeconds() int64 {
	if o == nil || IsNil(o.Seconds) {
		var ret int64
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobTimeTotal) GetSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.Seconds) {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *V0044JobTimeTotal) HasSeconds() bool {
	if o != nil && !IsNil(o.Seconds) {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int64 and assigns it to the Seconds field.
func (o *V0044JobTimeTotal) SetSeconds(v int64) {
	o.Seconds = &v
}

// GetMicroseconds returns the Microseconds field value if set, zero value otherwise.
func (o *V0044JobTimeTotal) GetMicroseconds() int64 {
	if o == nil || IsNil(o.Microseconds) {
		var ret int64
		return ret
	}
	return *o.Microseconds
}

// GetMicrosecondsOk returns a tuple with the Microseconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobTimeTotal) GetMicrosecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.Microseconds) {
		return nil, false
	}
	return o.Microseconds, true
}

// HasMicroseconds returns a boolean if a field has been set.
func (o *V0044JobTimeTotal) HasMicroseconds() bool {
	if o != nil && !IsNil(o.Microseconds) {
		return true
	}

	return false
}

// SetMicroseconds gets a reference to the given int64 and assigns it to the Microseconds field.
func (o *V0044JobTimeTotal) SetMicroseconds(v int64) {
	o.Microseconds = &v
}

func (o V0044JobTimeTotal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044JobTimeTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Seconds) {
		toSerialize["seconds"] = o.Seconds
	}
	if !IsNil(o.Microseconds) {
		toSerialize["microseconds"] = o.Microseconds
	}
	return toSerialize, nil
}

type NullableV0044JobTimeTotal struct {
	value *V0044JobTimeTotal
	isSet bool
}

func (v NullableV0044JobTimeTotal) Get() *V0044JobTimeTotal {
	return v.value
}

func (v *NullableV0044JobTimeTotal) Set(val *V0044JobTimeTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044JobTimeTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044JobTimeTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044JobTimeTotal(val *V0044JobTimeTotal) *NullableV0044JobTimeTotal {
	return &NullableV0044JobTimeTotal{value: val, isSet: true}
}

func (v NullableV0044JobTimeTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044JobTimeTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


