/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044OpenapiMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044OpenapiMeta{}

// V0044OpenapiMeta struct for V0044OpenapiMeta
type V0044OpenapiMeta struct {
	Plugin *V0044OpenapiMetaPlugin `json:"plugin,omitempty"`
	Client *V0044OpenapiMetaClient `json:"client,omitempty"`
	Command []string `json:"command,omitempty"`
	Slurm *V0044OpenapiMetaSlurm `json:"slurm,omitempty"`
}

// NewV0044OpenapiMeta instantiates a new V0044OpenapiMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044OpenapiMeta() *V0044OpenapiMeta {
	this := V0044OpenapiMeta{}
	return &this
}

// NewV0044OpenapiMetaWithDefaults instantiates a new V0044OpenapiMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044OpenapiMetaWithDefaults() *V0044OpenapiMeta {
	this := V0044OpenapiMeta{}
	return &this
}

// GetPlugin returns the Plugin field value if set, zero value otherwise.
func (o *V0044OpenapiMeta) GetPlugin() V0044OpenapiMetaPlugin {
	if o == nil || IsNil(o.Plugin) {
		var ret V0044OpenapiMetaPlugin
		return ret
	}
	return *o.Plugin
}

// GetPluginOk returns a tuple with the Plugin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiMeta) GetPluginOk() (*V0044OpenapiMetaPlugin, bool) {
	if o == nil || IsNil(o.Plugin) {
		return nil, false
	}
	return o.Plugin, true
}

// HasPlugin returns a boolean if a field has been set.
func (o *V0044OpenapiMeta) HasPlugin() bool {
	if o != nil && !IsNil(o.Plugin) {
		return true
	}

	return false
}

// SetPlugin gets a reference to the given V0044OpenapiMetaPlugin and assigns it to the Plugin field.
func (o *V0044OpenapiMeta) SetPlugin(v V0044OpenapiMetaPlugin) {
	o.Plugin = &v
}

// GetClient returns the Client field value if set, zero value otherwise.
func (o *V0044OpenapiMeta) GetClient() V0044OpenapiMetaClient {
	if o == nil || IsNil(o.Client) {
		var ret V0044OpenapiMetaClient
		return ret
	}
	return *o.Client
}

// GetClientOk returns a tuple with the Client field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiMeta) GetClientOk() (*V0044OpenapiMetaClient, bool) {
	if o == nil || IsNil(o.Client) {
		return nil, false
	}
	return o.Client, true
}

// HasClient returns a boolean if a field has been set.
func (o *V0044OpenapiMeta) HasClient() bool {
	if o != nil && !IsNil(o.Client) {
		return true
	}

	return false
}

// SetClient gets a reference to the given V0044OpenapiMetaClient and assigns it to the Client field.
func (o *V0044OpenapiMeta) SetClient(v V0044OpenapiMetaClient) {
	o.Client = &v
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *V0044OpenapiMeta) GetCommand() []string {
	if o == nil || IsNil(o.Command) {
		var ret []string
		return ret
	}
	return o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiMeta) GetCommandOk() ([]string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *V0044OpenapiMeta) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given []string and assigns it to the Command field.
func (o *V0044OpenapiMeta) SetCommand(v []string) {
	o.Command = v
}

// GetSlurm returns the Slurm field value if set, zero value otherwise.
func (o *V0044OpenapiMeta) GetSlurm() V0044OpenapiMetaSlurm {
	if o == nil || IsNil(o.Slurm) {
		var ret V0044OpenapiMetaSlurm
		return ret
	}
	return *o.Slurm
}

// GetSlurmOk returns a tuple with the Slurm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044OpenapiMeta) GetSlurmOk() (*V0044OpenapiMetaSlurm, bool) {
	if o == nil || IsNil(o.Slurm) {
		return nil, false
	}
	return o.Slurm, true
}

// HasSlurm returns a boolean if a field has been set.
func (o *V0044OpenapiMeta) HasSlurm() bool {
	if o != nil && !IsNil(o.Slurm) {
		return true
	}

	return false
}

// SetSlurm gets a reference to the given V0044OpenapiMetaSlurm and assigns it to the Slurm field.
func (o *V0044OpenapiMeta) SetSlurm(v V0044OpenapiMetaSlurm) {
	o.Slurm = &v
}

func (o V0044OpenapiMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044OpenapiMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plugin) {
		toSerialize["plugin"] = o.Plugin
	}
	if !IsNil(o.Client) {
		toSerialize["client"] = o.Client
	}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Slurm) {
		toSerialize["slurm"] = o.Slurm
	}
	return toSerialize, nil
}

type NullableV0044OpenapiMeta struct {
	value *V0044OpenapiMeta
	isSet bool
}

func (v NullableV0044OpenapiMeta) Get() *V0044OpenapiMeta {
	return v.value
}

func (v *NullableV0044OpenapiMeta) Set(val *V0044OpenapiMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044OpenapiMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044OpenapiMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044OpenapiMeta(val *V0044OpenapiMeta) *NullableV0044OpenapiMeta {
	return &NullableV0044OpenapiMeta{value: val, isSet: true}
}

func (v NullableV0044OpenapiMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044OpenapiMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


