/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044AssocDefault type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044AssocDefault{}

// V0044AssocDefault struct for V0044AssocDefault
type V0044AssocDefault struct {
	// Default QOS
	Qos *string `json:"qos,omitempty"`
}

// NewV0044AssocDefault instantiates a new V0044AssocDefault object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044AssocDefault() *V0044AssocDefault {
	this := V0044AssocDefault{}
	return &this
}

// NewV0044AssocDefaultWithDefaults instantiates a new V0044AssocDefault object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044AssocDefaultWithDefaults() *V0044AssocDefault {
	this := V0044AssocDefault{}
	return &this
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *V0044AssocDefault) GetQos() string {
	if o == nil || IsNil(o.Qos) {
		var ret string
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044AssocDefault) GetQosOk() (*string, bool) {
	if o == nil || IsNil(o.Qos) {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *V0044AssocDefault) HasQos() bool {
	if o != nil && !IsNil(o.Qos) {
		return true
	}

	return false
}

// SetQos gets a reference to the given string and assigns it to the Qos field.
func (o *V0044AssocDefault) SetQos(v string) {
	o.Qos = &v
}

func (o V0044AssocDefault) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044AssocDefault) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Qos) {
		toSerialize["qos"] = o.Qos
	}
	return toSerialize, nil
}

type NullableV0044AssocDefault struct {
	value *V0044AssocDefault
	isSet bool
}

func (v NullableV0044AssocDefault) Get() *V0044AssocDefault {
	return v.value
}

func (v *NullableV0044AssocDefault) Set(val *V0044AssocDefault) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044AssocDefault) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044AssocDefault) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044AssocDefault(val *V0044AssocDefault) *NullableV0044AssocDefault {
	return &NullableV0044AssocDefault{value: val, isSet: true}
}

func (v NullableV0044AssocDefault) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044AssocDefault) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


