/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * API version: 0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// V0037DiagStatistics Slurm statistics
type V0037DiagStatistics struct {
	// partition records packed
	PartsPacked *int32 `json:"parts_packed,omitempty"`
	// generation time
	ReqTime *int32 `json:"req_time,omitempty"`
	// data since
	ReqTimeStart *int32 `json:"req_time_start,omitempty"`
	// Server thread count
	ServerThreadCount *int32 `json:"server_thread_count,omitempty"`
	// Agent queue size
	AgentQueueSize *int32 `json:"agent_queue_size,omitempty"`
	// Agent count
	AgentCount *int32 `json:"agent_count,omitempty"`
	// Agent thread count
	AgentThreadCount *int32 `json:"agent_thread_count,omitempty"`
	// DBD Agent queue size
	DbdAgentQueueSize *int32 `json:"dbd_agent_queue_size,omitempty"`
	// Latency for 1000 calls to gettimeofday()
	GettimeofdayLatency *int32 `json:"gettimeofday_latency,omitempty"`
	// Main Schedule max cycle
	ScheduleCycleMax *int32 `json:"schedule_cycle_max,omitempty"`
	// Main Schedule last cycle
	ScheduleCycleLast *int32 `json:"schedule_cycle_last,omitempty"`
	// Main Schedule cycle iterations
	ScheduleCycleTotal *int32 `json:"schedule_cycle_total,omitempty"`
	// Average time for Schedule Max cycle
	ScheduleCycleMean *int32 `json:"schedule_cycle_mean,omitempty"`
	// Average depth for Schedule Max cycle
	ScheduleCycleMeanDepth *int32 `json:"schedule_cycle_mean_depth,omitempty"`
	// Main Schedule Cycles per minute
	ScheduleCyclePerMinute *int32 `json:"schedule_cycle_per_minute,omitempty"`
	// Main Schedule Last queue length
	ScheduleQueueLength *int32 `json:"schedule_queue_length,omitempty"`
	// Job submitted
	JobsSubmitted *int32 `json:"jobs_submitted,omitempty"`
	// Job started
	JobsStarted *int32 `json:"jobs_started,omitempty"`
	// Job completed
	JobsCompleted *int32 `json:"jobs_completed,omitempty"`
	// Job cancelled
	JobsCanceled *int32 `json:"jobs_canceled,omitempty"`
	// Job failed
	JobsFailed *int32 `json:"jobs_failed,omitempty"`
	// Job pending
	JobsPending *int32 `json:"jobs_pending,omitempty"`
	// Job running
	JobsRunning *int32 `json:"jobs_running,omitempty"`
	// Job states timestamp
	JobStatesTs *int32 `json:"job_states_ts,omitempty"`
	// Total backfilled jobs (since last slurm start)
	BfBackfilledJobs *int32 `json:"bf_backfilled_jobs,omitempty"`
	// Total backfilled jobs (since last stats cycle start)
	BfLastBackfilledJobs *int32 `json:"bf_last_backfilled_jobs,omitempty"`
	// Total backfilled heterogeneous job components
	BfBackfilledHetJobs *int32 `json:"bf_backfilled_het_jobs,omitempty"`
	// Backfill Schedule Total cycles
	BfCycleCounter *int32 `json:"bf_cycle_counter,omitempty"`
	// Backfill Schedule Mean cycle
	BfCycleMean *int32 `json:"bf_cycle_mean,omitempty"`
	// Backfill Schedule Max cycle time
	BfCycleMax *int32 `json:"bf_cycle_max,omitempty"`
	// Backfill Schedule Last depth cycle
	BfLastDepth *int32 `json:"bf_last_depth,omitempty"`
	// Backfill Schedule Mean cycle (try sched)
	BfLastDepthTry *int32 `json:"bf_last_depth_try,omitempty"`
	// Backfill Schedule Depth Mean
	BfDepthMean *int32 `json:"bf_depth_mean,omitempty"`
	// Backfill Schedule Depth Mean (try sched)
	BfDepthMeanTry *int32 `json:"bf_depth_mean_try,omitempty"`
	// Backfill Schedule Last cycle time
	BfCycleLast *int32 `json:"bf_cycle_last,omitempty"`
	// Backfill Schedule Last queue length
	BfQueueLen *int32 `json:"bf_queue_len,omitempty"`
	// Backfill Schedule Mean queue length
	BfQueueLenMean *int32 `json:"bf_queue_len_mean,omitempty"`
	// Backfill table size
	BfTableSize *int32 `json:"bf_table_size,omitempty"`
	// Backfill table mean
	BfTableSizeMean *int32 `json:"bf_table_size_mean,omitempty"`
	// Last cycle timestamp
	BfWhenLastCycle *int32 `json:"bf_when_last_cycle,omitempty"`
	// Backfill Schedule currently active
	BfActive *bool `json:"bf_active,omitempty"`
	// Remote Procedure Call statistics by message type
	RpcsMessageType *[]V0037DiagRpcm `json:"rpcs_message_type,omitempty"`
	// Remote Procedure Call statistics by user
	RpcsUser *[]V0037DiagRpcu `json:"rpcs_user,omitempty"`
}

// NewV0037DiagStatistics instantiates a new V0037DiagStatistics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0037DiagStatistics() *V0037DiagStatistics {
	this := V0037DiagStatistics{}
	return &this
}

// NewV0037DiagStatisticsWithDefaults instantiates a new V0037DiagStatistics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0037DiagStatisticsWithDefaults() *V0037DiagStatistics {
	this := V0037DiagStatistics{}
	return &this
}

// GetPartsPacked returns the PartsPacked field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetPartsPacked() int32 {
	if o == nil || o.PartsPacked == nil {
		var ret int32
		return ret
	}
	return *o.PartsPacked
}

// GetPartsPackedOk returns a tuple with the PartsPacked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetPartsPackedOk() (*int32, bool) {
	if o == nil || o.PartsPacked == nil {
		return nil, false
	}
	return o.PartsPacked, true
}

// HasPartsPacked returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasPartsPacked() bool {
	if o != nil && o.PartsPacked != nil {
		return true
	}

	return false
}

// SetPartsPacked gets a reference to the given int32 and assigns it to the PartsPacked field.
func (o *V0037DiagStatistics) SetPartsPacked(v int32) {
	o.PartsPacked = &v
}

// GetReqTime returns the ReqTime field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetReqTime() int32 {
	if o == nil || o.ReqTime == nil {
		var ret int32
		return ret
	}
	return *o.ReqTime
}

// GetReqTimeOk returns a tuple with the ReqTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetReqTimeOk() (*int32, bool) {
	if o == nil || o.ReqTime == nil {
		return nil, false
	}
	return o.ReqTime, true
}

// HasReqTime returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasReqTime() bool {
	if o != nil && o.ReqTime != nil {
		return true
	}

	return false
}

// SetReqTime gets a reference to the given int32 and assigns it to the ReqTime field.
func (o *V0037DiagStatistics) SetReqTime(v int32) {
	o.ReqTime = &v
}

// GetReqTimeStart returns the ReqTimeStart field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetReqTimeStart() int32 {
	if o == nil || o.ReqTimeStart == nil {
		var ret int32
		return ret
	}
	return *o.ReqTimeStart
}

// GetReqTimeStartOk returns a tuple with the ReqTimeStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetReqTimeStartOk() (*int32, bool) {
	if o == nil || o.ReqTimeStart == nil {
		return nil, false
	}
	return o.ReqTimeStart, true
}

// HasReqTimeStart returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasReqTimeStart() bool {
	if o != nil && o.ReqTimeStart != nil {
		return true
	}

	return false
}

// SetReqTimeStart gets a reference to the given int32 and assigns it to the ReqTimeStart field.
func (o *V0037DiagStatistics) SetReqTimeStart(v int32) {
	o.ReqTimeStart = &v
}

// GetServerThreadCount returns the ServerThreadCount field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetServerThreadCount() int32 {
	if o == nil || o.ServerThreadCount == nil {
		var ret int32
		return ret
	}
	return *o.ServerThreadCount
}

// GetServerThreadCountOk returns a tuple with the ServerThreadCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetServerThreadCountOk() (*int32, bool) {
	if o == nil || o.ServerThreadCount == nil {
		return nil, false
	}
	return o.ServerThreadCount, true
}

// HasServerThreadCount returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasServerThreadCount() bool {
	if o != nil && o.ServerThreadCount != nil {
		return true
	}

	return false
}

// SetServerThreadCount gets a reference to the given int32 and assigns it to the ServerThreadCount field.
func (o *V0037DiagStatistics) SetServerThreadCount(v int32) {
	o.ServerThreadCount = &v
}

// GetAgentQueueSize returns the AgentQueueSize field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetAgentQueueSize() int32 {
	if o == nil || o.AgentQueueSize == nil {
		var ret int32
		return ret
	}
	return *o.AgentQueueSize
}

// GetAgentQueueSizeOk returns a tuple with the AgentQueueSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetAgentQueueSizeOk() (*int32, bool) {
	if o == nil || o.AgentQueueSize == nil {
		return nil, false
	}
	return o.AgentQueueSize, true
}

// HasAgentQueueSize returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasAgentQueueSize() bool {
	if o != nil && o.AgentQueueSize != nil {
		return true
	}

	return false
}

// SetAgentQueueSize gets a reference to the given int32 and assigns it to the AgentQueueSize field.
func (o *V0037DiagStatistics) SetAgentQueueSize(v int32) {
	o.AgentQueueSize = &v
}

// GetAgentCount returns the AgentCount field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetAgentCount() int32 {
	if o == nil || o.AgentCount == nil {
		var ret int32
		return ret
	}
	return *o.AgentCount
}

// GetAgentCountOk returns a tuple with the AgentCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetAgentCountOk() (*int32, bool) {
	if o == nil || o.AgentCount == nil {
		return nil, false
	}
	return o.AgentCount, true
}

// HasAgentCount returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasAgentCount() bool {
	if o != nil && o.AgentCount != nil {
		return true
	}

	return false
}

// SetAgentCount gets a reference to the given int32 and assigns it to the AgentCount field.
func (o *V0037DiagStatistics) SetAgentCount(v int32) {
	o.AgentCount = &v
}

// GetAgentThreadCount returns the AgentThreadCount field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetAgentThreadCount() int32 {
	if o == nil || o.AgentThreadCount == nil {
		var ret int32
		return ret
	}
	return *o.AgentThreadCount
}

// GetAgentThreadCountOk returns a tuple with the AgentThreadCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetAgentThreadCountOk() (*int32, bool) {
	if o == nil || o.AgentThreadCount == nil {
		return nil, false
	}
	return o.AgentThreadCount, true
}

// HasAgentThreadCount returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasAgentThreadCount() bool {
	if o != nil && o.AgentThreadCount != nil {
		return true
	}

	return false
}

// SetAgentThreadCount gets a reference to the given int32 and assigns it to the AgentThreadCount field.
func (o *V0037DiagStatistics) SetAgentThreadCount(v int32) {
	o.AgentThreadCount = &v
}

// GetDbdAgentQueueSize returns the DbdAgentQueueSize field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetDbdAgentQueueSize() int32 {
	if o == nil || o.DbdAgentQueueSize == nil {
		var ret int32
		return ret
	}
	return *o.DbdAgentQueueSize
}

// GetDbdAgentQueueSizeOk returns a tuple with the DbdAgentQueueSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetDbdAgentQueueSizeOk() (*int32, bool) {
	if o == nil || o.DbdAgentQueueSize == nil {
		return nil, false
	}
	return o.DbdAgentQueueSize, true
}

// HasDbdAgentQueueSize returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasDbdAgentQueueSize() bool {
	if o != nil && o.DbdAgentQueueSize != nil {
		return true
	}

	return false
}

// SetDbdAgentQueueSize gets a reference to the given int32 and assigns it to the DbdAgentQueueSize field.
func (o *V0037DiagStatistics) SetDbdAgentQueueSize(v int32) {
	o.DbdAgentQueueSize = &v
}

// GetGettimeofdayLatency returns the GettimeofdayLatency field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetGettimeofdayLatency() int32 {
	if o == nil || o.GettimeofdayLatency == nil {
		var ret int32
		return ret
	}
	return *o.GettimeofdayLatency
}

// GetGettimeofdayLatencyOk returns a tuple with the GettimeofdayLatency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetGettimeofdayLatencyOk() (*int32, bool) {
	if o == nil || o.GettimeofdayLatency == nil {
		return nil, false
	}
	return o.GettimeofdayLatency, true
}

// HasGettimeofdayLatency returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasGettimeofdayLatency() bool {
	if o != nil && o.GettimeofdayLatency != nil {
		return true
	}

	return false
}

// SetGettimeofdayLatency gets a reference to the given int32 and assigns it to the GettimeofdayLatency field.
func (o *V0037DiagStatistics) SetGettimeofdayLatency(v int32) {
	o.GettimeofdayLatency = &v
}

// GetScheduleCycleMax returns the ScheduleCycleMax field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetScheduleCycleMax() int32 {
	if o == nil || o.ScheduleCycleMax == nil {
		var ret int32
		return ret
	}
	return *o.ScheduleCycleMax
}

// GetScheduleCycleMaxOk returns a tuple with the ScheduleCycleMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetScheduleCycleMaxOk() (*int32, bool) {
	if o == nil || o.ScheduleCycleMax == nil {
		return nil, false
	}
	return o.ScheduleCycleMax, true
}

// HasScheduleCycleMax returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasScheduleCycleMax() bool {
	if o != nil && o.ScheduleCycleMax != nil {
		return true
	}

	return false
}

// SetScheduleCycleMax gets a reference to the given int32 and assigns it to the ScheduleCycleMax field.
func (o *V0037DiagStatistics) SetScheduleCycleMax(v int32) {
	o.ScheduleCycleMax = &v
}

// GetScheduleCycleLast returns the ScheduleCycleLast field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetScheduleCycleLast() int32 {
	if o == nil || o.ScheduleCycleLast == nil {
		var ret int32
		return ret
	}
	return *o.ScheduleCycleLast
}

// GetScheduleCycleLastOk returns a tuple with the ScheduleCycleLast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetScheduleCycleLastOk() (*int32, bool) {
	if o == nil || o.ScheduleCycleLast == nil {
		return nil, false
	}
	return o.ScheduleCycleLast, true
}

// HasScheduleCycleLast returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasScheduleCycleLast() bool {
	if o != nil && o.ScheduleCycleLast != nil {
		return true
	}

	return false
}

// SetScheduleCycleLast gets a reference to the given int32 and assigns it to the ScheduleCycleLast field.
func (o *V0037DiagStatistics) SetScheduleCycleLast(v int32) {
	o.ScheduleCycleLast = &v
}

// GetScheduleCycleTotal returns the ScheduleCycleTotal field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetScheduleCycleTotal() int32 {
	if o == nil || o.ScheduleCycleTotal == nil {
		var ret int32
		return ret
	}
	return *o.ScheduleCycleTotal
}

// GetScheduleCycleTotalOk returns a tuple with the ScheduleCycleTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetScheduleCycleTotalOk() (*int32, bool) {
	if o == nil || o.ScheduleCycleTotal == nil {
		return nil, false
	}
	return o.ScheduleCycleTotal, true
}

// HasScheduleCycleTotal returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasScheduleCycleTotal() bool {
	if o != nil && o.ScheduleCycleTotal != nil {
		return true
	}

	return false
}

// SetScheduleCycleTotal gets a reference to the given int32 and assigns it to the ScheduleCycleTotal field.
func (o *V0037DiagStatistics) SetScheduleCycleTotal(v int32) {
	o.ScheduleCycleTotal = &v
}

// GetScheduleCycleMean returns the ScheduleCycleMean field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetScheduleCycleMean() int32 {
	if o == nil || o.ScheduleCycleMean == nil {
		var ret int32
		return ret
	}
	return *o.ScheduleCycleMean
}

// GetScheduleCycleMeanOk returns a tuple with the ScheduleCycleMean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetScheduleCycleMeanOk() (*int32, bool) {
	if o == nil || o.ScheduleCycleMean == nil {
		return nil, false
	}
	return o.ScheduleCycleMean, true
}

// HasScheduleCycleMean returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasScheduleCycleMean() bool {
	if o != nil && o.ScheduleCycleMean != nil {
		return true
	}

	return false
}

// SetScheduleCycleMean gets a reference to the given int32 and assigns it to the ScheduleCycleMean field.
func (o *V0037DiagStatistics) SetScheduleCycleMean(v int32) {
	o.ScheduleCycleMean = &v
}

// GetScheduleCycleMeanDepth returns the ScheduleCycleMeanDepth field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetScheduleCycleMeanDepth() int32 {
	if o == nil || o.ScheduleCycleMeanDepth == nil {
		var ret int32
		return ret
	}
	return *o.ScheduleCycleMeanDepth
}

// GetScheduleCycleMeanDepthOk returns a tuple with the ScheduleCycleMeanDepth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetScheduleCycleMeanDepthOk() (*int32, bool) {
	if o == nil || o.ScheduleCycleMeanDepth == nil {
		return nil, false
	}
	return o.ScheduleCycleMeanDepth, true
}

// HasScheduleCycleMeanDepth returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasScheduleCycleMeanDepth() bool {
	if o != nil && o.ScheduleCycleMeanDepth != nil {
		return true
	}

	return false
}

// SetScheduleCycleMeanDepth gets a reference to the given int32 and assigns it to the ScheduleCycleMeanDepth field.
func (o *V0037DiagStatistics) SetScheduleCycleMeanDepth(v int32) {
	o.ScheduleCycleMeanDepth = &v
}

// GetScheduleCyclePerMinute returns the ScheduleCyclePerMinute field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetScheduleCyclePerMinute() int32 {
	if o == nil || o.ScheduleCyclePerMinute == nil {
		var ret int32
		return ret
	}
	return *o.ScheduleCyclePerMinute
}

// GetScheduleCyclePerMinuteOk returns a tuple with the ScheduleCyclePerMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetScheduleCyclePerMinuteOk() (*int32, bool) {
	if o == nil || o.ScheduleCyclePerMinute == nil {
		return nil, false
	}
	return o.ScheduleCyclePerMinute, true
}

// HasScheduleCyclePerMinute returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasScheduleCyclePerMinute() bool {
	if o != nil && o.ScheduleCyclePerMinute != nil {
		return true
	}

	return false
}

// SetScheduleCyclePerMinute gets a reference to the given int32 and assigns it to the ScheduleCyclePerMinute field.
func (o *V0037DiagStatistics) SetScheduleCyclePerMinute(v int32) {
	o.ScheduleCyclePerMinute = &v
}

// GetScheduleQueueLength returns the ScheduleQueueLength field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetScheduleQueueLength() int32 {
	if o == nil || o.ScheduleQueueLength == nil {
		var ret int32
		return ret
	}
	return *o.ScheduleQueueLength
}

// GetScheduleQueueLengthOk returns a tuple with the ScheduleQueueLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetScheduleQueueLengthOk() (*int32, bool) {
	if o == nil || o.ScheduleQueueLength == nil {
		return nil, false
	}
	return o.ScheduleQueueLength, true
}

// HasScheduleQueueLength returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasScheduleQueueLength() bool {
	if o != nil && o.ScheduleQueueLength != nil {
		return true
	}

	return false
}

// SetScheduleQueueLength gets a reference to the given int32 and assigns it to the ScheduleQueueLength field.
func (o *V0037DiagStatistics) SetScheduleQueueLength(v int32) {
	o.ScheduleQueueLength = &v
}

// GetJobsSubmitted returns the JobsSubmitted field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobsSubmitted() int32 {
	if o == nil || o.JobsSubmitted == nil {
		var ret int32
		return ret
	}
	return *o.JobsSubmitted
}

// GetJobsSubmittedOk returns a tuple with the JobsSubmitted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobsSubmittedOk() (*int32, bool) {
	if o == nil || o.JobsSubmitted == nil {
		return nil, false
	}
	return o.JobsSubmitted, true
}

// HasJobsSubmitted returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobsSubmitted() bool {
	if o != nil && o.JobsSubmitted != nil {
		return true
	}

	return false
}

// SetJobsSubmitted gets a reference to the given int32 and assigns it to the JobsSubmitted field.
func (o *V0037DiagStatistics) SetJobsSubmitted(v int32) {
	o.JobsSubmitted = &v
}

// GetJobsStarted returns the JobsStarted field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobsStarted() int32 {
	if o == nil || o.JobsStarted == nil {
		var ret int32
		return ret
	}
	return *o.JobsStarted
}

// GetJobsStartedOk returns a tuple with the JobsStarted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobsStartedOk() (*int32, bool) {
	if o == nil || o.JobsStarted == nil {
		return nil, false
	}
	return o.JobsStarted, true
}

// HasJobsStarted returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobsStarted() bool {
	if o != nil && o.JobsStarted != nil {
		return true
	}

	return false
}

// SetJobsStarted gets a reference to the given int32 and assigns it to the JobsStarted field.
func (o *V0037DiagStatistics) SetJobsStarted(v int32) {
	o.JobsStarted = &v
}

// GetJobsCompleted returns the JobsCompleted field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobsCompleted() int32 {
	if o == nil || o.JobsCompleted == nil {
		var ret int32
		return ret
	}
	return *o.JobsCompleted
}

// GetJobsCompletedOk returns a tuple with the JobsCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobsCompletedOk() (*int32, bool) {
	if o == nil || o.JobsCompleted == nil {
		return nil, false
	}
	return o.JobsCompleted, true
}

// HasJobsCompleted returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobsCompleted() bool {
	if o != nil && o.JobsCompleted != nil {
		return true
	}

	return false
}

// SetJobsCompleted gets a reference to the given int32 and assigns it to the JobsCompleted field.
func (o *V0037DiagStatistics) SetJobsCompleted(v int32) {
	o.JobsCompleted = &v
}

// GetJobsCanceled returns the JobsCanceled field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobsCanceled() int32 {
	if o == nil || o.JobsCanceled == nil {
		var ret int32
		return ret
	}
	return *o.JobsCanceled
}

// GetJobsCanceledOk returns a tuple with the JobsCanceled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobsCanceledOk() (*int32, bool) {
	if o == nil || o.JobsCanceled == nil {
		return nil, false
	}
	return o.JobsCanceled, true
}

// HasJobsCanceled returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobsCanceled() bool {
	if o != nil && o.JobsCanceled != nil {
		return true
	}

	return false
}

// SetJobsCanceled gets a reference to the given int32 and assigns it to the JobsCanceled field.
func (o *V0037DiagStatistics) SetJobsCanceled(v int32) {
	o.JobsCanceled = &v
}

// GetJobsFailed returns the JobsFailed field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobsFailed() int32 {
	if o == nil || o.JobsFailed == nil {
		var ret int32
		return ret
	}
	return *o.JobsFailed
}

// GetJobsFailedOk returns a tuple with the JobsFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobsFailedOk() (*int32, bool) {
	if o == nil || o.JobsFailed == nil {
		return nil, false
	}
	return o.JobsFailed, true
}

// HasJobsFailed returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobsFailed() bool {
	if o != nil && o.JobsFailed != nil {
		return true
	}

	return false
}

// SetJobsFailed gets a reference to the given int32 and assigns it to the JobsFailed field.
func (o *V0037DiagStatistics) SetJobsFailed(v int32) {
	o.JobsFailed = &v
}

// GetJobsPending returns the JobsPending field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobsPending() int32 {
	if o == nil || o.JobsPending == nil {
		var ret int32
		return ret
	}
	return *o.JobsPending
}

// GetJobsPendingOk returns a tuple with the JobsPending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobsPendingOk() (*int32, bool) {
	if o == nil || o.JobsPending == nil {
		return nil, false
	}
	return o.JobsPending, true
}

// HasJobsPending returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobsPending() bool {
	if o != nil && o.JobsPending != nil {
		return true
	}

	return false
}

// SetJobsPending gets a reference to the given int32 and assigns it to the JobsPending field.
func (o *V0037DiagStatistics) SetJobsPending(v int32) {
	o.JobsPending = &v
}

// GetJobsRunning returns the JobsRunning field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobsRunning() int32 {
	if o == nil || o.JobsRunning == nil {
		var ret int32
		return ret
	}
	return *o.JobsRunning
}

// GetJobsRunningOk returns a tuple with the JobsRunning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobsRunningOk() (*int32, bool) {
	if o == nil || o.JobsRunning == nil {
		return nil, false
	}
	return o.JobsRunning, true
}

// HasJobsRunning returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobsRunning() bool {
	if o != nil && o.JobsRunning != nil {
		return true
	}

	return false
}

// SetJobsRunning gets a reference to the given int32 and assigns it to the JobsRunning field.
func (o *V0037DiagStatistics) SetJobsRunning(v int32) {
	o.JobsRunning = &v
}

// GetJobStatesTs returns the JobStatesTs field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetJobStatesTs() int32 {
	if o == nil || o.JobStatesTs == nil {
		var ret int32
		return ret
	}
	return *o.JobStatesTs
}

// GetJobStatesTsOk returns a tuple with the JobStatesTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetJobStatesTsOk() (*int32, bool) {
	if o == nil || o.JobStatesTs == nil {
		return nil, false
	}
	return o.JobStatesTs, true
}

// HasJobStatesTs returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasJobStatesTs() bool {
	if o != nil && o.JobStatesTs != nil {
		return true
	}

	return false
}

// SetJobStatesTs gets a reference to the given int32 and assigns it to the JobStatesTs field.
func (o *V0037DiagStatistics) SetJobStatesTs(v int32) {
	o.JobStatesTs = &v
}

// GetBfBackfilledJobs returns the BfBackfilledJobs field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfBackfilledJobs() int32 {
	if o == nil || o.BfBackfilledJobs == nil {
		var ret int32
		return ret
	}
	return *o.BfBackfilledJobs
}

// GetBfBackfilledJobsOk returns a tuple with the BfBackfilledJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfBackfilledJobsOk() (*int32, bool) {
	if o == nil || o.BfBackfilledJobs == nil {
		return nil, false
	}
	return o.BfBackfilledJobs, true
}

// HasBfBackfilledJobs returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfBackfilledJobs() bool {
	if o != nil && o.BfBackfilledJobs != nil {
		return true
	}

	return false
}

// SetBfBackfilledJobs gets a reference to the given int32 and assigns it to the BfBackfilledJobs field.
func (o *V0037DiagStatistics) SetBfBackfilledJobs(v int32) {
	o.BfBackfilledJobs = &v
}

// GetBfLastBackfilledJobs returns the BfLastBackfilledJobs field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfLastBackfilledJobs() int32 {
	if o == nil || o.BfLastBackfilledJobs == nil {
		var ret int32
		return ret
	}
	return *o.BfLastBackfilledJobs
}

// GetBfLastBackfilledJobsOk returns a tuple with the BfLastBackfilledJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfLastBackfilledJobsOk() (*int32, bool) {
	if o == nil || o.BfLastBackfilledJobs == nil {
		return nil, false
	}
	return o.BfLastBackfilledJobs, true
}

// HasBfLastBackfilledJobs returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfLastBackfilledJobs() bool {
	if o != nil && o.BfLastBackfilledJobs != nil {
		return true
	}

	return false
}

// SetBfLastBackfilledJobs gets a reference to the given int32 and assigns it to the BfLastBackfilledJobs field.
func (o *V0037DiagStatistics) SetBfLastBackfilledJobs(v int32) {
	o.BfLastBackfilledJobs = &v
}

// GetBfBackfilledHetJobs returns the BfBackfilledHetJobs field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfBackfilledHetJobs() int32 {
	if o == nil || o.BfBackfilledHetJobs == nil {
		var ret int32
		return ret
	}
	return *o.BfBackfilledHetJobs
}

// GetBfBackfilledHetJobsOk returns a tuple with the BfBackfilledHetJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfBackfilledHetJobsOk() (*int32, bool) {
	if o == nil || o.BfBackfilledHetJobs == nil {
		return nil, false
	}
	return o.BfBackfilledHetJobs, true
}

// HasBfBackfilledHetJobs returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfBackfilledHetJobs() bool {
	if o != nil && o.BfBackfilledHetJobs != nil {
		return true
	}

	return false
}

// SetBfBackfilledHetJobs gets a reference to the given int32 and assigns it to the BfBackfilledHetJobs field.
func (o *V0037DiagStatistics) SetBfBackfilledHetJobs(v int32) {
	o.BfBackfilledHetJobs = &v
}

// GetBfCycleCounter returns the BfCycleCounter field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfCycleCounter() int32 {
	if o == nil || o.BfCycleCounter == nil {
		var ret int32
		return ret
	}
	return *o.BfCycleCounter
}

// GetBfCycleCounterOk returns a tuple with the BfCycleCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfCycleCounterOk() (*int32, bool) {
	if o == nil || o.BfCycleCounter == nil {
		return nil, false
	}
	return o.BfCycleCounter, true
}

// HasBfCycleCounter returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfCycleCounter() bool {
	if o != nil && o.BfCycleCounter != nil {
		return true
	}

	return false
}

// SetBfCycleCounter gets a reference to the given int32 and assigns it to the BfCycleCounter field.
func (o *V0037DiagStatistics) SetBfCycleCounter(v int32) {
	o.BfCycleCounter = &v
}

// GetBfCycleMean returns the BfCycleMean field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfCycleMean() int32 {
	if o == nil || o.BfCycleMean == nil {
		var ret int32
		return ret
	}
	return *o.BfCycleMean
}

// GetBfCycleMeanOk returns a tuple with the BfCycleMean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfCycleMeanOk() (*int32, bool) {
	if o == nil || o.BfCycleMean == nil {
		return nil, false
	}
	return o.BfCycleMean, true
}

// HasBfCycleMean returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfCycleMean() bool {
	if o != nil && o.BfCycleMean != nil {
		return true
	}

	return false
}

// SetBfCycleMean gets a reference to the given int32 and assigns it to the BfCycleMean field.
func (o *V0037DiagStatistics) SetBfCycleMean(v int32) {
	o.BfCycleMean = &v
}

// GetBfCycleMax returns the BfCycleMax field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfCycleMax() int32 {
	if o == nil || o.BfCycleMax == nil {
		var ret int32
		return ret
	}
	return *o.BfCycleMax
}

// GetBfCycleMaxOk returns a tuple with the BfCycleMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfCycleMaxOk() (*int32, bool) {
	if o == nil || o.BfCycleMax == nil {
		return nil, false
	}
	return o.BfCycleMax, true
}

// HasBfCycleMax returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfCycleMax() bool {
	if o != nil && o.BfCycleMax != nil {
		return true
	}

	return false
}

// SetBfCycleMax gets a reference to the given int32 and assigns it to the BfCycleMax field.
func (o *V0037DiagStatistics) SetBfCycleMax(v int32) {
	o.BfCycleMax = &v
}

// GetBfLastDepth returns the BfLastDepth field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfLastDepth() int32 {
	if o == nil || o.BfLastDepth == nil {
		var ret int32
		return ret
	}
	return *o.BfLastDepth
}

// GetBfLastDepthOk returns a tuple with the BfLastDepth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfLastDepthOk() (*int32, bool) {
	if o == nil || o.BfLastDepth == nil {
		return nil, false
	}
	return o.BfLastDepth, true
}

// HasBfLastDepth returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfLastDepth() bool {
	if o != nil && o.BfLastDepth != nil {
		return true
	}

	return false
}

// SetBfLastDepth gets a reference to the given int32 and assigns it to the BfLastDepth field.
func (o *V0037DiagStatistics) SetBfLastDepth(v int32) {
	o.BfLastDepth = &v
}

// GetBfLastDepthTry returns the BfLastDepthTry field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfLastDepthTry() int32 {
	if o == nil || o.BfLastDepthTry == nil {
		var ret int32
		return ret
	}
	return *o.BfLastDepthTry
}

// GetBfLastDepthTryOk returns a tuple with the BfLastDepthTry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfLastDepthTryOk() (*int32, bool) {
	if o == nil || o.BfLastDepthTry == nil {
		return nil, false
	}
	return o.BfLastDepthTry, true
}

// HasBfLastDepthTry returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfLastDepthTry() bool {
	if o != nil && o.BfLastDepthTry != nil {
		return true
	}

	return false
}

// SetBfLastDepthTry gets a reference to the given int32 and assigns it to the BfLastDepthTry field.
func (o *V0037DiagStatistics) SetBfLastDepthTry(v int32) {
	o.BfLastDepthTry = &v
}

// GetBfDepthMean returns the BfDepthMean field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfDepthMean() int32 {
	if o == nil || o.BfDepthMean == nil {
		var ret int32
		return ret
	}
	return *o.BfDepthMean
}

// GetBfDepthMeanOk returns a tuple with the BfDepthMean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfDepthMeanOk() (*int32, bool) {
	if o == nil || o.BfDepthMean == nil {
		return nil, false
	}
	return o.BfDepthMean, true
}

// HasBfDepthMean returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfDepthMean() bool {
	if o != nil && o.BfDepthMean != nil {
		return true
	}

	return false
}

// SetBfDepthMean gets a reference to the given int32 and assigns it to the BfDepthMean field.
func (o *V0037DiagStatistics) SetBfDepthMean(v int32) {
	o.BfDepthMean = &v
}

// GetBfDepthMeanTry returns the BfDepthMeanTry field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfDepthMeanTry() int32 {
	if o == nil || o.BfDepthMeanTry == nil {
		var ret int32
		return ret
	}
	return *o.BfDepthMeanTry
}

// GetBfDepthMeanTryOk returns a tuple with the BfDepthMeanTry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfDepthMeanTryOk() (*int32, bool) {
	if o == nil || o.BfDepthMeanTry == nil {
		return nil, false
	}
	return o.BfDepthMeanTry, true
}

// HasBfDepthMeanTry returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfDepthMeanTry() bool {
	if o != nil && o.BfDepthMeanTry != nil {
		return true
	}

	return false
}

// SetBfDepthMeanTry gets a reference to the given int32 and assigns it to the BfDepthMeanTry field.
func (o *V0037DiagStatistics) SetBfDepthMeanTry(v int32) {
	o.BfDepthMeanTry = &v
}

// GetBfCycleLast returns the BfCycleLast field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfCycleLast() int32 {
	if o == nil || o.BfCycleLast == nil {
		var ret int32
		return ret
	}
	return *o.BfCycleLast
}

// GetBfCycleLastOk returns a tuple with the BfCycleLast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfCycleLastOk() (*int32, bool) {
	if o == nil || o.BfCycleLast == nil {
		return nil, false
	}
	return o.BfCycleLast, true
}

// HasBfCycleLast returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfCycleLast() bool {
	if o != nil && o.BfCycleLast != nil {
		return true
	}

	return false
}

// SetBfCycleLast gets a reference to the given int32 and assigns it to the BfCycleLast field.
func (o *V0037DiagStatistics) SetBfCycleLast(v int32) {
	o.BfCycleLast = &v
}

// GetBfQueueLen returns the BfQueueLen field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfQueueLen() int32 {
	if o == nil || o.BfQueueLen == nil {
		var ret int32
		return ret
	}
	return *o.BfQueueLen
}

// GetBfQueueLenOk returns a tuple with the BfQueueLen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfQueueLenOk() (*int32, bool) {
	if o == nil || o.BfQueueLen == nil {
		return nil, false
	}
	return o.BfQueueLen, true
}

// HasBfQueueLen returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfQueueLen() bool {
	if o != nil && o.BfQueueLen != nil {
		return true
	}

	return false
}

// SetBfQueueLen gets a reference to the given int32 and assigns it to the BfQueueLen field.
func (o *V0037DiagStatistics) SetBfQueueLen(v int32) {
	o.BfQueueLen = &v
}

// GetBfQueueLenMean returns the BfQueueLenMean field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfQueueLenMean() int32 {
	if o == nil || o.BfQueueLenMean == nil {
		var ret int32
		return ret
	}
	return *o.BfQueueLenMean
}

// GetBfQueueLenMeanOk returns a tuple with the BfQueueLenMean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfQueueLenMeanOk() (*int32, bool) {
	if o == nil || o.BfQueueLenMean == nil {
		return nil, false
	}
	return o.BfQueueLenMean, true
}

// HasBfQueueLenMean returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfQueueLenMean() bool {
	if o != nil && o.BfQueueLenMean != nil {
		return true
	}

	return false
}

// SetBfQueueLenMean gets a reference to the given int32 and assigns it to the BfQueueLenMean field.
func (o *V0037DiagStatistics) SetBfQueueLenMean(v int32) {
	o.BfQueueLenMean = &v
}

// GetBfTableSize returns the BfTableSize field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfTableSize() int32 {
	if o == nil || o.BfTableSize == nil {
		var ret int32
		return ret
	}
	return *o.BfTableSize
}

// GetBfTableSizeOk returns a tuple with the BfTableSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfTableSizeOk() (*int32, bool) {
	if o == nil || o.BfTableSize == nil {
		return nil, false
	}
	return o.BfTableSize, true
}

// HasBfTableSize returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfTableSize() bool {
	if o != nil && o.BfTableSize != nil {
		return true
	}

	return false
}

// SetBfTableSize gets a reference to the given int32 and assigns it to the BfTableSize field.
func (o *V0037DiagStatistics) SetBfTableSize(v int32) {
	o.BfTableSize = &v
}

// GetBfTableSizeMean returns the BfTableSizeMean field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfTableSizeMean() int32 {
	if o == nil || o.BfTableSizeMean == nil {
		var ret int32
		return ret
	}
	return *o.BfTableSizeMean
}

// GetBfTableSizeMeanOk returns a tuple with the BfTableSizeMean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfTableSizeMeanOk() (*int32, bool) {
	if o == nil || o.BfTableSizeMean == nil {
		return nil, false
	}
	return o.BfTableSizeMean, true
}

// HasBfTableSizeMean returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfTableSizeMean() bool {
	if o != nil && o.BfTableSizeMean != nil {
		return true
	}

	return false
}

// SetBfTableSizeMean gets a reference to the given int32 and assigns it to the BfTableSizeMean field.
func (o *V0037DiagStatistics) SetBfTableSizeMean(v int32) {
	o.BfTableSizeMean = &v
}

// GetBfWhenLastCycle returns the BfWhenLastCycle field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfWhenLastCycle() int32 {
	if o == nil || o.BfWhenLastCycle == nil {
		var ret int32
		return ret
	}
	return *o.BfWhenLastCycle
}

// GetBfWhenLastCycleOk returns a tuple with the BfWhenLastCycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfWhenLastCycleOk() (*int32, bool) {
	if o == nil || o.BfWhenLastCycle == nil {
		return nil, false
	}
	return o.BfWhenLastCycle, true
}

// HasBfWhenLastCycle returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfWhenLastCycle() bool {
	if o != nil && o.BfWhenLastCycle != nil {
		return true
	}

	return false
}

// SetBfWhenLastCycle gets a reference to the given int32 and assigns it to the BfWhenLastCycle field.
func (o *V0037DiagStatistics) SetBfWhenLastCycle(v int32) {
	o.BfWhenLastCycle = &v
}

// GetBfActive returns the BfActive field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetBfActive() bool {
	if o == nil || o.BfActive == nil {
		var ret bool
		return ret
	}
	return *o.BfActive
}

// GetBfActiveOk returns a tuple with the BfActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetBfActiveOk() (*bool, bool) {
	if o == nil || o.BfActive == nil {
		return nil, false
	}
	return o.BfActive, true
}

// HasBfActive returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasBfActive() bool {
	if o != nil && o.BfActive != nil {
		return true
	}

	return false
}

// SetBfActive gets a reference to the given bool and assigns it to the BfActive field.
func (o *V0037DiagStatistics) SetBfActive(v bool) {
	o.BfActive = &v
}

// GetRpcsMessageType returns the RpcsMessageType field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetRpcsMessageType() []V0037DiagRpcm {
	if o == nil || o.RpcsMessageType == nil {
		var ret []V0037DiagRpcm
		return ret
	}
	return *o.RpcsMessageType
}

// GetRpcsMessageTypeOk returns a tuple with the RpcsMessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetRpcsMessageTypeOk() (*[]V0037DiagRpcm, bool) {
	if o == nil || o.RpcsMessageType == nil {
		return nil, false
	}
	return o.RpcsMessageType, true
}

// HasRpcsMessageType returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasRpcsMessageType() bool {
	if o != nil && o.RpcsMessageType != nil {
		return true
	}

	return false
}

// SetRpcsMessageType gets a reference to the given []V0037DiagRpcm and assigns it to the RpcsMessageType field.
func (o *V0037DiagStatistics) SetRpcsMessageType(v []V0037DiagRpcm) {
	o.RpcsMessageType = &v
}

// GetRpcsUser returns the RpcsUser field value if set, zero value otherwise.
func (o *V0037DiagStatistics) GetRpcsUser() []V0037DiagRpcu {
	if o == nil || o.RpcsUser == nil {
		var ret []V0037DiagRpcu
		return ret
	}
	return *o.RpcsUser
}

// GetRpcsUserOk returns a tuple with the RpcsUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagStatistics) GetRpcsUserOk() (*[]V0037DiagRpcu, bool) {
	if o == nil || o.RpcsUser == nil {
		return nil, false
	}
	return o.RpcsUser, true
}

// HasRpcsUser returns a boolean if a field has been set.
func (o *V0037DiagStatistics) HasRpcsUser() bool {
	if o != nil && o.RpcsUser != nil {
		return true
	}

	return false
}

// SetRpcsUser gets a reference to the given []V0037DiagRpcu and assigns it to the RpcsUser field.
func (o *V0037DiagStatistics) SetRpcsUser(v []V0037DiagRpcu) {
	o.RpcsUser = &v
}

func (o V0037DiagStatistics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PartsPacked != nil {
		toSerialize["parts_packed"] = o.PartsPacked
	}
	if o.ReqTime != nil {
		toSerialize["req_time"] = o.ReqTime
	}
	if o.ReqTimeStart != nil {
		toSerialize["req_time_start"] = o.ReqTimeStart
	}
	if o.ServerThreadCount != nil {
		toSerialize["server_thread_count"] = o.ServerThreadCount
	}
	if o.AgentQueueSize != nil {
		toSerialize["agent_queue_size"] = o.AgentQueueSize
	}
	if o.AgentCount != nil {
		toSerialize["agent_count"] = o.AgentCount
	}
	if o.AgentThreadCount != nil {
		toSerialize["agent_thread_count"] = o.AgentThreadCount
	}
	if o.DbdAgentQueueSize != nil {
		toSerialize["dbd_agent_queue_size"] = o.DbdAgentQueueSize
	}
	if o.GettimeofdayLatency != nil {
		toSerialize["gettimeofday_latency"] = o.GettimeofdayLatency
	}
	if o.ScheduleCycleMax != nil {
		toSerialize["schedule_cycle_max"] = o.ScheduleCycleMax
	}
	if o.ScheduleCycleLast != nil {
		toSerialize["schedule_cycle_last"] = o.ScheduleCycleLast
	}
	if o.ScheduleCycleTotal != nil {
		toSerialize["schedule_cycle_total"] = o.ScheduleCycleTotal
	}
	if o.ScheduleCycleMean != nil {
		toSerialize["schedule_cycle_mean"] = o.ScheduleCycleMean
	}
	if o.ScheduleCycleMeanDepth != nil {
		toSerialize["schedule_cycle_mean_depth"] = o.ScheduleCycleMeanDepth
	}
	if o.ScheduleCyclePerMinute != nil {
		toSerialize["schedule_cycle_per_minute"] = o.ScheduleCyclePerMinute
	}
	if o.ScheduleQueueLength != nil {
		toSerialize["schedule_queue_length"] = o.ScheduleQueueLength
	}
	if o.JobsSubmitted != nil {
		toSerialize["jobs_submitted"] = o.JobsSubmitted
	}
	if o.JobsStarted != nil {
		toSerialize["jobs_started"] = o.JobsStarted
	}
	if o.JobsCompleted != nil {
		toSerialize["jobs_completed"] = o.JobsCompleted
	}
	if o.JobsCanceled != nil {
		toSerialize["jobs_canceled"] = o.JobsCanceled
	}
	if o.JobsFailed != nil {
		toSerialize["jobs_failed"] = o.JobsFailed
	}
	if o.JobsPending != nil {
		toSerialize["jobs_pending"] = o.JobsPending
	}
	if o.JobsRunning != nil {
		toSerialize["jobs_running"] = o.JobsRunning
	}
	if o.JobStatesTs != nil {
		toSerialize["job_states_ts"] = o.JobStatesTs
	}
	if o.BfBackfilledJobs != nil {
		toSerialize["bf_backfilled_jobs"] = o.BfBackfilledJobs
	}
	if o.BfLastBackfilledJobs != nil {
		toSerialize["bf_last_backfilled_jobs"] = o.BfLastBackfilledJobs
	}
	if o.BfBackfilledHetJobs != nil {
		toSerialize["bf_backfilled_het_jobs"] = o.BfBackfilledHetJobs
	}
	if o.BfCycleCounter != nil {
		toSerialize["bf_cycle_counter"] = o.BfCycleCounter
	}
	if o.BfCycleMean != nil {
		toSerialize["bf_cycle_mean"] = o.BfCycleMean
	}
	if o.BfCycleMax != nil {
		toSerialize["bf_cycle_max"] = o.BfCycleMax
	}
	if o.BfLastDepth != nil {
		toSerialize["bf_last_depth"] = o.BfLastDepth
	}
	if o.BfLastDepthTry != nil {
		toSerialize["bf_last_depth_try"] = o.BfLastDepthTry
	}
	if o.BfDepthMean != nil {
		toSerialize["bf_depth_mean"] = o.BfDepthMean
	}
	if o.BfDepthMeanTry != nil {
		toSerialize["bf_depth_mean_try"] = o.BfDepthMeanTry
	}
	if o.BfCycleLast != nil {
		toSerialize["bf_cycle_last"] = o.BfCycleLast
	}
	if o.BfQueueLen != nil {
		toSerialize["bf_queue_len"] = o.BfQueueLen
	}
	if o.BfQueueLenMean != nil {
		toSerialize["bf_queue_len_mean"] = o.BfQueueLenMean
	}
	if o.BfTableSize != nil {
		toSerialize["bf_table_size"] = o.BfTableSize
	}
	if o.BfTableSizeMean != nil {
		toSerialize["bf_table_size_mean"] = o.BfTableSizeMean
	}
	if o.BfWhenLastCycle != nil {
		toSerialize["bf_when_last_cycle"] = o.BfWhenLastCycle
	}
	if o.BfActive != nil {
		toSerialize["bf_active"] = o.BfActive
	}
	if o.RpcsMessageType != nil {
		toSerialize["rpcs_message_type"] = o.RpcsMessageType
	}
	if o.RpcsUser != nil {
		toSerialize["rpcs_user"] = o.RpcsUser
	}
	return json.Marshal(toSerialize)
}

type NullableV0037DiagStatistics struct {
	value *V0037DiagStatistics
	isSet bool
}

func (v NullableV0037DiagStatistics) Get() *V0037DiagStatistics {
	return v.value
}

func (v *NullableV0037DiagStatistics) Set(val *V0037DiagStatistics) {
	v.value = val
	v.isSet = true
}

func (v NullableV0037DiagStatistics) IsSet() bool {
	return v.isSet
}

func (v *NullableV0037DiagStatistics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0037DiagStatistics(val *V0037DiagStatistics) *NullableV0037DiagStatistics {
	return &NullableV0037DiagStatistics{value: val, isSet: true}
}

func (v NullableV0037DiagStatistics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0037DiagStatistics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


