/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044StepTasks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044StepTasks{}

// V0044StepTasks struct for V0044StepTasks
type V0044StepTasks struct {
	// Total number of tasks
	Count *int32 `json:"count,omitempty"`
}

// NewV0044StepTasks instantiates a new V0044StepTasks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044StepTasks() *V0044StepTasks {
	this := V0044StepTasks{}
	return &this
}

// NewV0044StepTasksWithDefaults instantiates a new V0044StepTasks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044StepTasksWithDefaults() *V0044StepTasks {
	this := V0044StepTasks{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *V0044StepTasks) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTasks) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *V0044StepTasks) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *V0044StepTasks) SetCount(v int32) {
	o.Count = &v
}

func (o V0044StepTasks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044StepTasks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableV0044StepTasks struct {
	value *V0044StepTasks
	isSet bool
}

func (v NullableV0044StepTasks) Get() *V0044StepTasks {
	return v.value
}

func (v *NullableV0044StepTasks) Set(val *V0044StepTasks) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044StepTasks) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044StepTasks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044StepTasks(val *V0044StepTasks) *NullableV0044StepTasks {
	return &NullableV0044StepTasks{value: val, isSet: true}
}

func (v NullableV0044StepTasks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044StepTasks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


