/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044StepTask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044StepTask{}

// V0044StepTask struct for V0044StepTask
type V0044StepTask struct {
	// The layout of the step was when it was running
	Distribution *string `json:"distribution,omitempty"`
}

// NewV0044StepTask instantiates a new V0044StepTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044StepTask() *V0044StepTask {
	this := V0044StepTask{}
	return &this
}

// NewV0044StepTaskWithDefaults instantiates a new V0044StepTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044StepTaskWithDefaults() *V0044StepTask {
	this := V0044StepTask{}
	return &this
}

// GetDistribution returns the Distribution field value if set, zero value otherwise.
func (o *V0044StepTask) GetDistribution() string {
	if o == nil || IsNil(o.Distribution) {
		var ret string
		return ret
	}
	return *o.Distribution
}

// GetDistributionOk returns a tuple with the Distribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTask) GetDistributionOk() (*string, bool) {
	if o == nil || IsNil(o.Distribution) {
		return nil, false
	}
	return o.Distribution, true
}

// HasDistribution returns a boolean if a field has been set.
func (o *V0044StepTask) HasDistribution() bool {
	if o != nil && !IsNil(o.Distribution) {
		return true
	}

	return false
}

// SetDistribution gets a reference to the given string and assigns it to the Distribution field.
func (o *V0044StepTask) SetDistribution(v string) {
	o.Distribution = &v
}

func (o V0044StepTask) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044StepTask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Distribution) {
		toSerialize["distribution"] = o.Distribution
	}
	return toSerialize, nil
}

type NullableV0044StepTask struct {
	value *V0044StepTask
	isSet bool
}

func (v NullableV0044StepTask) Get() *V0044StepTask {
	return v.value
}

func (v *NullableV0044StepTask) Set(val *V0044StepTask) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044StepTask) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044StepTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044StepTask(val *V0044StepTask) *NullableV0044StepTask {
	return &NullableV0044StepTask{value: val, isSet: true}
}

func (v NullableV0044StepTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044StepTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


