/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.2&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0041OpenapiKillJobsRespStatusInnerFederation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiKillJobsRespStatusInnerFederation{}

// V0041OpenapiKillJobsRespStatusInnerFederation struct for V0041OpenapiKillJobsRespStatusInnerFederation
type V0041OpenapiKillJobsRespStatusInnerFederation struct {
	// Name of federation sibling (may be empty for non-federation)
	Sibling *string `json:"sibling,omitempty"`
}

// NewV0041OpenapiKillJobsRespStatusInnerFederation instantiates a new V0041OpenapiKillJobsRespStatusInnerFederation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiKillJobsRespStatusInnerFederation() *V0041OpenapiKillJobsRespStatusInnerFederation {
	this := V0041OpenapiKillJobsRespStatusInnerFederation{}
	return &this
}

// NewV0041OpenapiKillJobsRespStatusInnerFederationWithDefaults instantiates a new V0041OpenapiKillJobsRespStatusInnerFederation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiKillJobsRespStatusInnerFederationWithDefaults() *V0041OpenapiKillJobsRespStatusInnerFederation {
	this := V0041OpenapiKillJobsRespStatusInnerFederation{}
	return &this
}

// GetSibling returns the Sibling field value if set, zero value otherwise.
func (o *V0041OpenapiKillJobsRespStatusInnerFederation) GetSibling() string {
	if o == nil || IsNil(o.Sibling) {
		var ret string
		return ret
	}
	return *o.Sibling
}

// GetSiblingOk returns a tuple with the Sibling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiKillJobsRespStatusInnerFederation) GetSiblingOk() (*string, bool) {
	if o == nil || IsNil(o.Sibling) {
		return nil, false
	}
	return o.Sibling, true
}

// HasSibling returns a boolean if a field has been set.
func (o *V0041OpenapiKillJobsRespStatusInnerFederation) HasSibling() bool {
	if o != nil && !IsNil(o.Sibling) {
		return true
	}

	return false
}

// SetSibling gets a reference to the given string and assigns it to the Sibling field.
func (o *V0041OpenapiKillJobsRespStatusInnerFederation) SetSibling(v string) {
	o.Sibling = &v
}

func (o V0041OpenapiKillJobsRespStatusInnerFederation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiKillJobsRespStatusInnerFederation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sibling) {
		toSerialize["sibling"] = o.Sibling
	}
	return toSerialize, nil
}

type NullableV0041OpenapiKillJobsRespStatusInnerFederation struct {
	value *V0041OpenapiKillJobsRespStatusInnerFederation
	isSet bool
}

func (v NullableV0041OpenapiKillJobsRespStatusInnerFederation) Get() *V0041OpenapiKillJobsRespStatusInnerFederation {
	return v.value
}

func (v *NullableV0041OpenapiKillJobsRespStatusInnerFederation) Set(val *V0041OpenapiKillJobsRespStatusInnerFederation) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiKillJobsRespStatusInnerFederation) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiKillJobsRespStatusInnerFederation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiKillJobsRespStatusInnerFederation(val *V0041OpenapiKillJobsRespStatusInnerFederation) *NullableV0041OpenapiKillJobsRespStatusInnerFederation {
	return &NullableV0041OpenapiKillJobsRespStatusInnerFederation{value: val, isSet: true}
}

func (v NullableV0041OpenapiKillJobsRespStatusInnerFederation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiKillJobsRespStatusInnerFederation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


