/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044RollupStatsDailyDuration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044RollupStatsDailyDuration{}

// V0044RollupStatsDailyDuration struct for V0044RollupStatsDailyDuration
type V0044RollupStatsDailyDuration struct {
	// Total time spent doing daily daily rollup (seconds)
	Last *int64 `json:"last,omitempty"`
	// Longest daily rollup time (seconds)
	Max *int64 `json:"max,omitempty"`
	// Total time spent doing daily rollups (seconds)
	Time *int64 `json:"time,omitempty"`
}

// NewV0044RollupStatsDailyDuration instantiates a new V0044RollupStatsDailyDuration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044RollupStatsDailyDuration() *V0044RollupStatsDailyDuration {
	this := V0044RollupStatsDailyDuration{}
	return &this
}

// NewV0044RollupStatsDailyDurationWithDefaults instantiates a new V0044RollupStatsDailyDuration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044RollupStatsDailyDurationWithDefaults() *V0044RollupStatsDailyDuration {
	this := V0044RollupStatsDailyDuration{}
	return &this
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *V0044RollupStatsDailyDuration) GetLast() int64 {
	if o == nil || IsNil(o.Last) {
		var ret int64
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044RollupStatsDailyDuration) GetLastOk() (*int64, bool) {
	if o == nil || IsNil(o.Last) {
		return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *V0044RollupStatsDailyDuration) HasLast() bool {
	if o != nil && !IsNil(o.Last) {
		return true
	}

	return false
}

// SetLast gets a reference to the given int64 and assigns it to the Last field.
func (o *V0044RollupStatsDailyDuration) SetLast(v int64) {
	o.Last = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *V0044RollupStatsDailyDuration) GetMax() int64 {
	if o == nil || IsNil(o.Max) {
		var ret int64
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044RollupStatsDailyDuration) GetMaxOk() (*int64, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *V0044RollupStatsDailyDuration) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given int64 and assigns it to the Max field.
func (o *V0044RollupStatsDailyDuration) SetMax(v int64) {
	o.Max = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *V0044RollupStatsDailyDuration) GetTime() int64 {
	if o == nil || IsNil(o.Time) {
		var ret int64
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044RollupStatsDailyDuration) GetTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *V0044RollupStatsDailyDuration) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given int64 and assigns it to the Time field.
func (o *V0044RollupStatsDailyDuration) SetTime(v int64) {
	o.Time = &v
}

func (o V0044RollupStatsDailyDuration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044RollupStatsDailyDuration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Last) {
		toSerialize["last"] = o.Last
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableV0044RollupStatsDailyDuration struct {
	value *V0044RollupStatsDailyDuration
	isSet bool
}

func (v NullableV0044RollupStatsDailyDuration) Get() *V0044RollupStatsDailyDuration {
	return v.value
}

func (v *NullableV0044RollupStatsDailyDuration) Set(val *V0044RollupStatsDailyDuration) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044RollupStatsDailyDuration) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044RollupStatsDailyDuration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044RollupStatsDailyDuration(val *V0044RollupStatsDailyDuration) *NullableV0044RollupStatsDailyDuration {
	return &NullableV0044RollupStatsDailyDuration{value: val, isSet: true}
}

func (v NullableV0044RollupStatsDailyDuration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044RollupStatsDailyDuration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


