/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * API version: 0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// V0037Diag struct for V0037Diag
type V0037Diag struct {
	// slurm errors
	Errors *[]V0037Error `json:"errors,omitempty"`
	Statistics *V0037DiagStatistics `json:"statistics,omitempty"`
}

// NewV0037Diag instantiates a new V0037Diag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0037Diag() *V0037Diag {
	this := V0037Diag{}
	return &this
}

// NewV0037DiagWithDefaults instantiates a new V0037Diag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0037DiagWithDefaults() *V0037Diag {
	this := V0037Diag{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0037Diag) GetErrors() []V0037Error {
	if o == nil || o.Errors == nil {
		var ret []V0037Error
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037Diag) GetErrorsOk() (*[]V0037Error, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0037Diag) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0037Error and assigns it to the Errors field.
func (o *V0037Diag) SetErrors(v []V0037Error) {
	o.Errors = &v
}

// GetStatistics returns the Statistics field value if set, zero value otherwise.
func (o *V0037Diag) GetStatistics() V0037DiagStatistics {
	if o == nil || o.Statistics == nil {
		var ret V0037DiagStatistics
		return ret
	}
	return *o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037Diag) GetStatisticsOk() (*V0037DiagStatistics, bool) {
	if o == nil || o.Statistics == nil {
		return nil, false
	}
	return o.Statistics, true
}

// HasStatistics returns a boolean if a field has been set.
func (o *V0037Diag) HasStatistics() bool {
	if o != nil && o.Statistics != nil {
		return true
	}

	return false
}

// SetStatistics gets a reference to the given V0037DiagStatistics and assigns it to the Statistics field.
func (o *V0037Diag) SetStatistics(v V0037DiagStatistics) {
	o.Statistics = &v
}

func (o V0037Diag) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Statistics != nil {
		toSerialize["statistics"] = o.Statistics
	}
	return json.Marshal(toSerialize)
}

type NullableV0037Diag struct {
	value *V0037Diag
	isSet bool
}

func (v NullableV0037Diag) Get() *V0037Diag {
	return v.value
}

func (v *NullableV0037Diag) Set(val *V0037Diag) {
	v.value = val
	v.isSet = true
}

func (v NullableV0037Diag) IsSet() bool {
	return v.isSet
}

func (v *NullableV0037Diag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0037Diag(val *V0037Diag) *NullableV0037Diag {
	return &NullableV0037Diag{value: val, isSet: true}
}

func (v NullableV0037Diag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0037Diag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


