/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.2&openapi/dbv0.0.39&openapi/v0.0.39&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode{}

// V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode return code returned by process
type V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode struct {
	// Status given by return code
	Status []string `json:"status,omitempty"`
	ReturnCode *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeReturnCode `json:"return_code,omitempty"`
	Signal *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeSignal `json:"signal,omitempty"`
}

// NewV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode instantiates a new V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode() *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode {
	this := V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode{}
	return &this
}

// NewV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeWithDefaults instantiates a new V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeWithDefaults() *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode {
	this := V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) GetStatus() []string {
	if o == nil || IsNil(o.Status) {
		var ret []string
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) GetStatusOk() ([]string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []string and assigns it to the Status field.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) SetStatus(v []string) {
	o.Status = v
}

// GetReturnCode returns the ReturnCode field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) GetReturnCode() V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeReturnCode {
	if o == nil || IsNil(o.ReturnCode) {
		var ret V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeReturnCode
		return ret
	}
	return *o.ReturnCode
}

// GetReturnCodeOk returns a tuple with the ReturnCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) GetReturnCodeOk() (*V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeReturnCode, bool) {
	if o == nil || IsNil(o.ReturnCode) {
		return nil, false
	}
	return o.ReturnCode, true
}

// HasReturnCode returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) HasReturnCode() bool {
	if o != nil && !IsNil(o.ReturnCode) {
		return true
	}

	return false
}

// SetReturnCode gets a reference to the given V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeReturnCode and assigns it to the ReturnCode field.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) SetReturnCode(v V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeReturnCode) {
	o.ReturnCode = &v
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) GetSignal() V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeSignal {
	if o == nil || IsNil(o.Signal) {
		var ret V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeSignal
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) GetSignalOk() (*V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeSignal, bool) {
	if o == nil || IsNil(o.Signal) {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) HasSignal() bool {
	if o != nil && !IsNil(o.Signal) {
		return true
	}

	return false
}

// SetSignal gets a reference to the given V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeSignal and assigns it to the Signal field.
func (o *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) SetSignal(v V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCodeSignal) {
	o.Signal = &v
}

func (o V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ReturnCode) {
		toSerialize["return_code"] = o.ReturnCode
	}
	if !IsNil(o.Signal) {
		toSerialize["signal"] = o.Signal
	}
	return toSerialize, nil
}

type NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode struct {
	value *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) Get() *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) Set(val *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode(val *V0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) *NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode {
	return &NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespJobsInnerDerivedExitCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


