/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044StepTimeTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044StepTimeTotal{}

// V0044StepTimeTotal struct for V0044StepTimeTotal
type V0044StepTimeTotal struct {
	// Total CPU time used by the step in seconds
	Seconds *int64 `json:"seconds,omitempty"`
	// Total CPU time used by the step in microseconds
	Microseconds *int32 `json:"microseconds,omitempty"`
}

// NewV0044StepTimeTotal instantiates a new V0044StepTimeTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044StepTimeTotal() *V0044StepTimeTotal {
	this := V0044StepTimeTotal{}
	return &this
}

// NewV0044StepTimeTotalWithDefaults instantiates a new V0044StepTimeTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044StepTimeTotalWithDefaults() *V0044StepTimeTotal {
	this := V0044StepTimeTotal{}
	return &this
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *V0044StepTimeTotal) GetSeconds() int64 {
	if o == nil || IsNil(o.Seconds) {
		var ret int64
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTimeTotal) GetSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.Seconds) {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *V0044StepTimeTotal) HasSeconds() bool {
	if o != nil && !IsNil(o.Seconds) {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int64 and assigns it to the Seconds field.
func (o *V0044StepTimeTotal) SetSeconds(v int64) {
	o.Seconds = &v
}

// GetMicroseconds returns the Microseconds field value if set, zero value otherwise.
func (o *V0044StepTimeTotal) GetMicroseconds() int32 {
	if o == nil || IsNil(o.Microseconds) {
		var ret int32
		return ret
	}
	return *o.Microseconds
}

// GetMicrosecondsOk returns a tuple with the Microseconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044StepTimeTotal) GetMicrosecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.Microseconds) {
		return nil, false
	}
	return o.Microseconds, true
}

// HasMicroseconds returns a boolean if a field has been set.
func (o *V0044StepTimeTotal) HasMicroseconds() bool {
	if o != nil && !IsNil(o.Microseconds) {
		return true
	}

	return false
}

// SetMicroseconds gets a reference to the given int32 and assigns it to the Microseconds field.
func (o *V0044StepTimeTotal) SetMicroseconds(v int32) {
	o.Microseconds = &v
}

func (o V0044StepTimeTotal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044StepTimeTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Seconds) {
		toSerialize["seconds"] = o.Seconds
	}
	if !IsNil(o.Microseconds) {
		toSerialize["microseconds"] = o.Microseconds
	}
	return toSerialize, nil
}

type NullableV0044StepTimeTotal struct {
	value *V0044StepTimeTotal
	isSet bool
}

func (v NullableV0044StepTimeTotal) Get() *V0044StepTimeTotal {
	return v.value
}

func (v *NullableV0044StepTimeTotal) Set(val *V0044StepTimeTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044StepTimeTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044StepTimeTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044StepTimeTotal(val *V0044StepTimeTotal) *NullableV0044StepTimeTotal {
	return &NullableV0044StepTimeTotal{value: val, isSet: true}
}

func (v NullableV0044StepTimeTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044StepTimeTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


