/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.11.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmrest

import (
	"encoding/json"
)

// checks if the V0044JobArrayLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0044JobArrayLimits{}

// V0044JobArrayLimits struct for V0044JobArrayLimits
type V0044JobArrayLimits struct {
	Max *V0044JobArrayLimitsMax `json:"max,omitempty"`
}

// NewV0044JobArrayLimits instantiates a new V0044JobArrayLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0044JobArrayLimits() *V0044JobArrayLimits {
	this := V0044JobArrayLimits{}
	return &this
}

// NewV0044JobArrayLimitsWithDefaults instantiates a new V0044JobArrayLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0044JobArrayLimitsWithDefaults() *V0044JobArrayLimits {
	this := V0044JobArrayLimits{}
	return &this
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *V0044JobArrayLimits) GetMax() V0044JobArrayLimitsMax {
	if o == nil || IsNil(o.Max) {
		var ret V0044JobArrayLimitsMax
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0044JobArrayLimits) GetMaxOk() (*V0044JobArrayLimitsMax, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *V0044JobArrayLimits) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given V0044JobArrayLimitsMax and assigns it to the Max field.
func (o *V0044JobArrayLimits) SetMax(v V0044JobArrayLimitsMax) {
	o.Max = &v
}

func (o V0044JobArrayLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0044JobArrayLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	return toSerialize, nil
}

type NullableV0044JobArrayLimits struct {
	value *V0044JobArrayLimits
	isSet bool
}

func (v NullableV0044JobArrayLimits) Get() *V0044JobArrayLimits {
	return v.value
}

func (v *NullableV0044JobArrayLimits) Set(val *V0044JobArrayLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableV0044JobArrayLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableV0044JobArrayLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0044JobArrayLimits(val *V0044JobArrayLimits) *NullableV0044JobArrayLimits {
	return &NullableV0044JobArrayLimits{value: val, isSet: true}
}

func (v NullableV0044JobArrayLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0044JobArrayLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


